document: feedback-pipeline-workload
version: 1
data:
  name: RHEL Image EC2 HA
  description: Packages in the RHEL Image EC2 HA
  maintainer: tdawson@redhat.com
  architectures:
    - x86_64
  packages:
    - NetworkManager
    - NetworkManager-tui
    - amd-gpu-firmware
    - audit
    - authselect
    - basesystem
    - bash
    - coreutils
    - cronie
    - crypto-policies
    - crypto-policies-scripts
    - curl
    - dnf
    - dnf-plugins-core
    - e2fsprogs
    - filesystem
    - glibc
    - grubby
    - hostname
    - initscripts-rename-device
    - insights-client
    - intel-gpu-firmware
    - iproute
    - iproute-tc
    - iputils
    - irqbalance
    - iwlwifi-dvm-firmware
    - iwlwifi-mvm-firmware
    - kbd
    - kernel-tools
    - kexec-tools
    - less
    - libsysfs
    - linux-firmware
    - logrotate
    - lshw
    - lsscsi
    - man-db
    - microcode_ctl
    - ncurses
    - nvidia-gpu-firmware
    - openssh-clients
    - openssh-server
    - p11-kit
    - parted
    - policycoreutils
    - prefixdevname
    - procps-ng
    - python3-libselinux
    - rhc
    - rootfiles
    - rpm
    - rpm-plugin-audit
    - rsyslog
    - selinux-policy-targeted
    - setup
    - sg3_utils
    - sg3_utils-libs
    - shadow-utils
    - sssd-common
    - sssd-kcm
    - sudo
    - systemd
    - util-linux
    - vim-minimal
    - xfsprogs
    - yum
    - NetworkManager-cloud-setup
    - chrony
    - cloud-init
    - cloud-utils-growpart
    - dhcpcd
    - dosfstools
    - dracut-config-generic
    - efibootmgr
    - fence-agents-all
    - grub2
    - grub2-efi-x64
    - grub2-pc
    - insights-client
    - kernel
    - langpacks-en
    - pacemaker
    - pcs
    - redhat-release
    - redhat-release-eula
    - rsync
    - selinux-policy-targeted
    - shim-x64
    - system-reinstall-bootc
    - tar
    - tuned
    - xfsprogs
    - yum-utils
  labels:
    - eln
    - c10s
