document: feedback-pipeline-workload
version: 1
data:
  name: RHEL Image WSL
  description: Packages in the RHEL Image WSL
  maintainer: tdawson@redhat.com
  architectures:
    - aarch64
    - x86_64
  packages:
    - alternatives
    - audit-libs
    - basesystem
    - bash
    - ca-certificates
    - cloud-init
    - coreutils-single
    - crypto-policies-scripts
    - curl-minimal
    - dejavu-sans-fonts
    - dnf
    - filesystem
    - findutils
    - gdb-gdbserver
    - glibc-minimal-langpack
    - gmp
    - gnupg2
    - gobject-introspection
    - hostname
    - langpacks-en
    - libcurl-minimal
    - openssh-server
    - openssl
    - pam
    - passwd
    - procps-ng
    - python3
    - python3-inotify
    - redhat-logos
    - redhat-release
    - rootfiles
    - rpm
    - sed
    - setup
    - shadow-utils
    - subscription-manager
    - sudo
    - systemd
    - tar
    - tpm2-tss
    - tzdata
    - util-linux
    - vim-minimal
    - yum
  labels:
    - eln
    - c10s
